-- MySQL Script generated by MySQL Workbench
-- Thu Jan 14 09:09:05 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema lpmdjee
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema lpmdjee
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `lpmdjee` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema shareloc
-- -----------------------------------------------------
USE `lpmdjee` ;

-- -----------------------------------------------------
-- Table `lpmdjee`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lpmdjee`.`User` ;

CREATE TABLE IF NOT EXISTS `lpmdjee`.`User` (
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `firstname` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`email`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lpmdjee`.`Colocation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lpmdjee`.`Colocation` ;

CREATE TABLE IF NOT EXISTS `lpmdjee`.`Colocation` (
  `idColocation` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idColocation`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lpmdjee`.`UserColocation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lpmdjee`.`UserColocation` ;

CREATE TABLE IF NOT EXISTS `lpmdjee`.`UserColocation` (
  `isManager` TINYINT NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `idColocation` INT NOT NULL,
  PRIMARY KEY (`email`, `idColocation`),
  CONSTRAINT `fk_UserColocation_User`
    FOREIGN KEY (`email`)
    REFERENCES `lpmdjee`.`User` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_UserColocation_Colocation1`
    FOREIGN KEY (`idColocation`)
    REFERENCES `lpmdjee`.`Colocation` (`idColocation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lpmdjee`.`UserColocation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lpmdjee`.`UserColocation` ;

CREATE TABLE IF NOT EXISTS `lpmdjee`.`UserColocation` (
  `isManager` TINYINT NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `idColocation` INT NOT NULL,
  PRIMARY KEY (`email`, `idColocation`),
  CONSTRAINT `fk_UserColocation_User`
    FOREIGN KEY (`email`)
    REFERENCES `lpmdjee`.`User` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_UserColocation_Colocation1`
    FOREIGN KEY (`idColocation`)
    REFERENCES `lpmdjee`.`Colocation` (`idColocation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lpmdjee`.`Task`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lpmdjee`.`Task` ;

CREATE TABLE IF NOT EXISTS `lpmdjee`.`Task` (
  `idTask` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(255) NULL,
  `cost` INT NULL,
  `idColocation` INT NOT NULL,
  PRIMARY KEY (`idTask`),
  CONSTRAINT `fk_Task_Colocation1`
    FOREIGN KEY (`idColocation`)
    REFERENCES `lpmdjee`.`Colocation` (`idColocation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lpmdjee`.`Service`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lpmdjee`.`Service` ;

CREATE TABLE IF NOT EXISTS `lpmdjee`.`Service` (
  `email` VARCHAR(255) NOT NULL,
  `idTask` INT NOT NULL,
  `date` DATETIME NOT NULL,
  `image` BLOB NULL,
  `isValide` TINYINT NULL,
  PRIMARY KEY (`email`, `idTask`),
  CONSTRAINT `fk_Service_User1`
    FOREIGN KEY (`email`)
    REFERENCES `lpmdjee`.`User` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Service_Task1`
    FOREIGN KEY (`idTask`)
    REFERENCES `lpmdjee`.`Task` (`idTask`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lpmdjee`.`Recipients`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lpmdjee`.`Recipients` ;

CREATE TABLE IF NOT EXISTS `lpmdjee`.`Recipients` (
  `emailWorker` VARCHAR(255) NOT NULL,
  `idTask` INT NOT NULL,
  `emailRecipients` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`emailWorker`, `idTask`, `emailRecipients`),
  CONSTRAINT `fk_Recipients_Service1`
    FOREIGN KEY (`emailWorker` , `idTask`)
    REFERENCES `lpmdjee`.`Service` (`email` , `idTask`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Recipients_User1`
    FOREIGN KEY (`emailRecipients`)
    REFERENCES `lpmdjee`.`User` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lpmdjee`.`VoteDelete`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lpmdjee`.`VoteDelete` ;

CREATE TABLE IF NOT EXISTS `lpmdjee`.`VoteDelete` (
  `email` VARCHAR(255) NOT NULL,
  `idTask` INT NOT NULL,
  `vote` TINYINT NOT NULL,
  PRIMARY KEY (`email`, `idTask`),
  CONSTRAINT `fk_VoteAdd_User1`
    FOREIGN KEY (`email`)
    REFERENCES `lpmdjee`.`User` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_VoteAdd_Task1`
    FOREIGN KEY (`idTask`)
    REFERENCES `lpmdjee`.`Task` (`idTask`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lpmdjee`.`VoteAdd`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lpmdjee`.`VoteAdd` ;

CREATE TABLE IF NOT EXISTS `lpmdjee`.`VoteAdd` (
  `email` VARCHAR(255) NOT NULL,
  `idTask` INT NOT NULL,
  `vote` TINYINT NOT NULL,
  PRIMARY KEY (`email`, `idTask`),
  CONSTRAINT `fk_VoteAdd_User2`
    FOREIGN KEY (`email`)
    REFERENCES `lpmdjee`.`User` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_VoteAdd_Task2`
    FOREIGN KEY (`idTask`)
    REFERENCES `lpmdjee`.`Task` (`idTask`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
