-- MySQL Script generated by MySQL Workbench
-- Thu Jan  7 16:01:11 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema shareloc
-- -----------------------------------------------------
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`User` (
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `firstname` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`email`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Colocation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Colocation` (
  `idColocation` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idColocation`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`UserColocation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`UserColocation` (
  `isManager` TINYINT NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `idColocation` INT NOT NULL,
  PRIMARY KEY (`email`, `idColocation`),
  INDEX `fk_UserColocation_Colocation1_idx` (`idColocation` ASC) VISIBLE,
  CONSTRAINT `fk_UserColocation_User`
    FOREIGN KEY (`email`)
    REFERENCES `mydb`.`User` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_UserColocation_Colocation1`
    FOREIGN KEY (`idColocation`)
    REFERENCES `mydb`.`Colocation` (`idColocation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`UserColocation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`UserColocation` (
  `isManager` TINYINT NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `idColocation` INT NOT NULL,
  PRIMARY KEY (`email`, `idColocation`),
  INDEX `fk_UserColocation_Colocation1_idx` (`idColocation` ASC) VISIBLE,
  CONSTRAINT `fk_UserColocation_User`
    FOREIGN KEY (`email`)
    REFERENCES `mydb`.`User` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_UserColocation_Colocation1`
    FOREIGN KEY (`idColocation`)
    REFERENCES `mydb`.`Colocation` (`idColocation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Task`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Task` (
  `idTask` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(255) NULL,
  `cost` INT NULL,
  `idColocation` INT NOT NULL,
  PRIMARY KEY (`idTask`),
  INDEX `fk_Task_Colocation1_idx` (`idColocation` ASC) VISIBLE,
  CONSTRAINT `fk_Task_Colocation1`
    FOREIGN KEY (`idColocation`)
    REFERENCES `mydb`.`Colocation` (`idColocation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Service`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Service` (
  `email` VARCHAR(255) NOT NULL,
  `idTask` INT NOT NULL,
  `date` DATETIME NOT NULL,
  `image` BLOB NULL,
  `isValide` TINYINT NULL,
  PRIMARY KEY (`email`, `idTask`),
  INDEX `fk_Service_Task1_idx` (`idTask` ASC) VISIBLE,
  CONSTRAINT `fk_Service_User1`
    FOREIGN KEY (`email`)
    REFERENCES `mydb`.`User` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Service_Task1`
    FOREIGN KEY (`idTask`)
    REFERENCES `mydb`.`Task` (`idTask`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Recipients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Recipients` (
  `emailWorker` VARCHAR(255) NOT NULL,
  `idTask` INT NOT NULL,
  `emailRecipients` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`emailWorker`, `idTask`, `emailRecipients`),
  INDEX `fk_Recipients_User1_idx` (`emailRecipients` ASC) VISIBLE,
  CONSTRAINT `fk_Recipients_Service1`
    FOREIGN KEY (`emailWorker` , `idTask`)
    REFERENCES `mydb`.`Service` (`email` , `idTask`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Recipients_User1`
    FOREIGN KEY (`emailRecipients`)
    REFERENCES `mydb`.`User` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`VoteDelete`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`VoteDelete` (
  `email` VARCHAR(255) NOT NULL,
  `idTask` INT NOT NULL,
  `vote` TINYINT NOT NULL,
  PRIMARY KEY (`email`, `idTask`),
  INDEX `fk_VoteAdd_Task1_idx` (`idTask` ASC) VISIBLE,
  CONSTRAINT `fk_VoteAdd_User1`
    FOREIGN KEY (`email`)
    REFERENCES `mydb`.`User` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_VoteAdd_Task1`
    FOREIGN KEY (`idTask`)
    REFERENCES `mydb`.`Task` (`idTask`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`VoteAdd`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`VoteAdd` (
  `email` VARCHAR(255) NOT NULL,
  `idTask` INT NOT NULL,
  `vote` TINYINT NOT NULL,
  PRIMARY KEY (`email`, `idTask`),
  INDEX `fk_VoteAdd_Task2_idx` (`idTask` ASC) VISIBLE,
  CONSTRAINT `fk_VoteAdd_User2`
    FOREIGN KEY (`email`)
    REFERENCES `mydb`.`User` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_VoteAdd_Task2`
    FOREIGN KEY (`idTask`)
    REFERENCES `mydb`.`Task` (`idTask`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
